# https://about.gitlab.com/2016/04/07/gitlab-pages-setup/

image:
  - node:8-slim
  - openjdk:8-jre-slim

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm run dirs
  - npm run build
  - cp -rT dist public
  artifacts:
    paths:
    - public
  only:
    - master
