# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
  - mkdir -p dist/css dist/js
  - npm install
  - npm run build:html
  artifacts:
    paths:
    - dist
  only:
  - master
