# https://about.gitlab.com/2016/04/07/gitlab-pages-setup/

image: node:8-slim

pages:
  cache:
    paths:
    - node_modules/

  script:
  - apt-get update && apt-get install default-jre-headless openjdk-8-jre-headless
  - npm install
  - npm run dirs
  - npm run build
  - cp -rT dist public
  artifacts:
    paths:
    - public
  only:
    - master
